export const core = [
  {
    avatar: 'https://www.github.com/yyx990803.png',
    name: 'Evan You',
    title: 'Творець',
    org: 'Vue.js',
    orgLink: 'https://vuejs.org/',
    desc: 'Незалежний розробник з відкритим кодом, творець Vue.js та Vite.',
    links: [
      { icon: 'github', link: 'https://github.com/yyx990803' },
      { icon: 'x', link: 'https://x.com/youyuxi' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/evanyou.me' },
    ],
    sponsor: 'https://github.com/sponsors/yyx990803',
  },
  {
    avatar: 'https://www.github.com/patak-dev.png',
    name: 'Patak',
    title: 'Співпрацююча істота',
    org: 'StackBlitz',
    orgLink: 'https://stackblitz.com/',
    desc: 'Член основної команди Vite. Член команди Vue.',
    links: [
      { icon: 'github', link: 'https://github.com/patak-dev' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/patak.dev' },
      { icon: 'mastodon', link: 'https://elk.zone/m.webtoo.ls/@patak' },
    ],
    sponsor: 'https://github.com/sponsors/patak-dev',
  },
  {
    avatar: 'https://www.github.com/antfu.png',
    name: 'Anthony Fu',
    title: 'Фанатичний розробник з відкритим кодом',
    org: 'NuxtLabs',
    orgLink: 'https://nuxtlabs.com/',
    desc: 'Член основної команди Vite та Vue. Працюю в NuxtLabs.',
    links: [
      { icon: 'github', link: 'https://github.com/antfu' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/antfu.me' },
      { icon: 'mastodon', link: 'https://elk.zone/m.webtoo.ls/@antfu' },
    ],
    sponsor: 'https://github.com/sponsors/antfu',
  },
  {
    avatar: 'https://github.com/bluwy.png',
    name: 'Bjorn Lu',
    title: 'Розробник з відкритим кодом',
    desc: 'Член основної команди Vite, Astro та Svelte.',
    links: [
      { icon: 'github', link: 'https://github.com/bluwy' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/bluwy.me' },
      { icon: 'twitter', link: 'https://twitter.com/bluwyoo' },
      { icon: 'mastodon', link: 'https://elk.zone/m.webtoo.ls/@bluwy' },
    ],
    sponsor: 'https://bjornlu.com/sponsor',
  },
  {
    avatar: 'https://github.com/sapphi-red.png',
    name: 'green',
    title: 'Веб-розробник',
    desc: 'Член основної команди Vite. Називайте мене sapphi, green або midori ;)',
    links: [
      { icon: 'github', link: 'https://github.com/sapphi-red' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/sapphi.red' },
      { icon: 'twitter', link: 'https://twitter.com/sapphi_red' },
      { icon: 'mastodon', link: 'https://elk.zone/m.webtoo.ls/@sapphi_red' },
    ],
    sponsor: 'https://github.com/sponsors/sapphi-red',
  },
  {
    avatar: 'https://github.com/ArnaudBarre.png',
    name: 'Arnaud Barré',
    title: 'Фронтенд розробник',
    desc: 'Захоплююсь інструментами навколо TypeScript та React.',
    links: [
      { icon: 'github', link: 'https://github.com/ArnaudBarre' },
      {
        icon: 'bluesky',
        link: 'https://bsky.app/profile/arnaud-barre.bsky.social',
      },
      { icon: 'mastodon', link: 'https://elk.zone/m.webtoo.ls/@ArnaudBarre' },
    ],
    sponsor: 'https://github.com/sponsors/ArnaudBarre',
  },
  {
    avatar: 'https://github.com/dominikg.png',
    name: 'Dominik G.',
    title: 'Експерт з CI',
    desc: 'Член команди Vite та Svelte.',
    links: [
      { icon: 'github', link: 'https://github.com/dominikg' },
      { icon: 'mastodon', link: 'https://elk.zone/m.webtoo.ls/@dominikg' },
    ],
    sponsor: 'https://github.com/sponsors/dominikg',
  },
  {
    avatar: 'https://github.com/sheremet-va.png',
    name: 'Vladimir',
    title: 'Член основної команди Vitest та Vite',
    desc: 'Розробник з відкритим кодом.',
    links: [
      { icon: 'github', link: 'https://github.com/sheremet-va' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/erus.dev' },
      { icon: 'mastodon', link: 'https://elk.zone/m.webtoo.ls/@sheremet_va' },
    ],
    sponsor: 'https://github.com/sponsors/sheremet-va',
  },
  {
    avatar: 'https://github.com/hi-ogawa.png',
    name: 'Hiroshi Ogawa',
    title: 'Член команди Vitest та Vite',
    desc: 'Ентузіаст з відкритим кодом.',
    links: [
      { icon: 'github', link: 'https://github.com/hi-ogawa' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/hiogawa.bsky.social' },
    ],
    sponsor: 'https://github.com/sponsors/hi-ogawa',
  },
]

export const emeriti = [
  {
    avatar: 'https://i.imgur.com/KMed6rQ.jpeg',
    name: 'Alec Larson',
    title: 'Підприємець',
    desc: 'Займаюсь соціальною електронною комерцією, мета-фреймворками та настільними іграми.',
    links: [
      { icon: 'github', link: 'https://github.com/aleclarson' },
      { icon: 'x', link: 'https://x.com/retropragma' },
      {
        icon: 'bluesky',
        link: 'https://bsky.app/profile/retropragma.bsky.social',
      },
    ],
  },
  {
    avatar: 'https://github.com/poyoho.png',
    name: 'yoho',
    title: 'Фронтенд розробник',
    desc: 'Фронтенд. Член команди Vite.',
    links: [
      { icon: 'github', link: 'https://github.com/poyoho' },
      { icon: 'x', link: 'https://x.com/yoho_po' },
    ],
  },
  {
    avatar: 'https://github.com/ygj6.png',
    name: 'ygj6',
    title: 'Розробник',
    desc: 'Веб-розробник. Член команди Vue та Vite.',
    links: [
      { icon: 'github', link: 'https://github.com/ygj6' },
      { icon: 'x', link: 'https://x.com/ygj_66' },
    ],
  },
  {
    avatar: 'https://github.com/Niputi.png',
    name: 'Niputi',
    title: 'Розробник',
    org: 'Computershare Denmark',
    desc: 'Люблю аніме та JavaScript.',
    links: [
      { icon: 'github', link: 'https://github.com/Niputi' },
      { icon: 'x', link: 'https://x.com/Niputi_' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/niputi.bsky.social' },
    ],
  },
  {
    avatar: 'https://github.com/underfin.png',
    name: 'underfin',
    title: 'Розробник',
    links: [{ icon: 'github', link: 'https://github.com/underfin' }],
  },
  {
    avatar: 'https://github.com/GrygrFlzr.png',
    name: 'GrygrFlzr',
    title: 'Розробник',
    links: [
      { icon: 'github', link: 'https://github.com/GrygrFlzr' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/bsky.cybeast.dev' },
    ],
  },
  {
    avatar: 'https://github.com/nihalgonsalves.png',
    name: 'Nihal Gonsalves',
    title: 'Старший програміст',
    links: [{ icon: 'github', link: 'https://github.com/nihalgonsalves' }],
  },
  {
    avatar: 'https://github.com/Shinigami92.png',
    name: 'Shinigami',
    title: 'Старший фронтенд розробник',
    org: 'Faker',
    orgLink: 'https://fakerjs.dev',
    desc: 'Пристрасний ентузіаст TypeScript, який активно працює з Vue SPA.',
    links: [
      { icon: 'github', link: 'https://github.com/Shinigami92' },
      { icon: 'mastodon', link: 'https://elk.zone/mas.to/@Shini92' },
    ],
  },
  {
    avatar: 'https://github.com/haoqunjiang.png',
    name: 'Haoqun Jiang',
    title: 'Член основної команди',
    org: 'Vue.js',
    orgLink: 'https://vuejs.org/',
    desc: 'Куратор найкращих практик для інструментів Vue.js.',
    links: [
      { icon: 'github', link: 'https://github.com/haoqunjiang' },
      { icon: 'bluesky', link: 'https://bsky.app/profile/haoqun.dev' },
      { icon: 'mastodon', link: 'https://elk.zone/m.webtoo.ls/@haoqun' },
    ],
    sponsor: 'https://github.com/sponsors/haoqunjiang',
  },
]
